export type BlockType =
    "Markdown"
    | "Code"
    | "Image"
    | "Video"
    | "Audio"
    | "File"
    | "Embed"
    | "Table"
    | "List"
    | "Quote"
    | "Divider"
    | "Equation"
    | "Mathematica"